spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ainotes
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    show-sql: true

logging:
  level:
    com.gtr3.ANote: DEBUG
    org.hibernate.SQL: DEBUG
